# Generated by Django 3.2.12 on 2022-06-05 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_up',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
